### ISSUE TITLE
ProfileScreen example infer  minHeight and maxHeight

### ISSUE THREAD

**Issue by takasurazeem** [exyte/ScalingHeaderScrollView#15]
Is it possible to infer the min and max height for the header without specifying it? I am trying to have a `UIViewRepresentable` as a large and small header but their height cannot be calculated for some reason and they are dynamic in nature.

**Comment by f3dm76** [comment]
Hey @takasurazeem, it is impossible for the library to assume your desired max and min heights, since API only accepts one view builder for the header, so one can interpolate their changes smoothly. If you want to use two different views for expanded and collapsed header, please use GeometryReader to calculate your header's sizes and pass it to the library
