### ISSUE TITLE
Add the ability to clip scroll view content

### ISSUE THREAD

**Issue by dmitryLagoda** [exyte/ScalingHeaderScrollView#48]
Thank you for this and other your amazing libraries! 
May be you could help me to resolve one annoying issue: clipping/masking the content of a scroll view. I want that scroll view content has rounded corners and clipped to that shape. This might be even not related to your library, but so far I completely stuck. Would be appreciated any suggestions. 
This is the effect I want to achieve (it's working in ios17 using .mask and .visualEffect modifiers), but I have to target ios 16, so I am looking for an alternative solution. 
Video:
https://github.com/exyte/ScalingHeaderScrollView/assets/2717056/9c0a28db-b924-408b-af15-e94893d2fbfe
Photo:
<img width="396" alt="Screenshot 2024-01-09 at 18 36 20" src="https://github.com/exyte/ScalingHeaderScrollView/assets/2717056/3a5a2a1d-5929-451e-9944-e17ad875dda8">

And this is the best I could achieve with your library. 
<img width="355" alt="Screenshot 2024-01-09 at 18 26 20" src="https://github.com/exyte/ScalingHeaderScrollView/assets/2717056/59edf0cf-fccc-42c4-af2b-64e374c11e91">

Thank you for making our work much easier with your libraries!

**Comment by f3dm76** [comment]
Hey @dmitryLagoda, thank you very much for your kind words. If I understood correctly you can clip it, but you cannot make the header be seen in the corners. In this case I think one of the gifs in this project (profile one, with Alisa Millford) shows your rounded corners use-case. The trick there is to make the rounded corners part of the header itself rather than the content. But you can also try using negative padding for the content. Have a wonderful day!

**Comment by dmitryLagoda** [comment]
Thank you, Alisa! I tried to put the rounded rectangle to the header, that didn't look nice in my case, but may be I should give it another shot. Anyway, I'll take a look on it again.
